application: redhorse4you
version: 1
runtime: python
api_version: 1

handlers:
- url: /datasoftware/.*
  script: datasoftware.py

- url: /data123/.*
  script: data123.py

- url: /.*
  script: redhorse4you.py

